// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS3nIkvWigQnUxcRkudJoHSy5NW29cIic',
    appId: '1:651011193231:web:40187b646c3534f22e73fa',
    messagingSenderId: '651011193231',
    projectId: 'kiet-olx',
    authDomain: 'kiet-olx.firebaseapp.com',
    storageBucket: 'kiet-olx.appspot.com',
    measurementId: 'G-EZRT0R0W6M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy3jDIVCRsoO7ohNMbrWMs2FJofjK7-bU',
    appId: '1:651011193231:android:9ed1a24baa3507bc2e73fa',
    messagingSenderId: '651011193231',
    projectId: 'kiet-olx',
    storageBucket: 'kiet-olx.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuCekFB9dNxA0Mq8DJ2bafF1sx_agHw1U',
    appId: '1:651011193231:ios:c5ca6c509c92cfc22e73fa',
    messagingSenderId: '651011193231',
    projectId: 'kiet-olx',
    storageBucket: 'kiet-olx.appspot.com',
    iosClientId: '651011193231-8h5of7ct9ofkoj41huf7cphck3igccsk.apps.googleusercontent.com',
    iosBundleId: 'com.example.kietOlx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuCekFB9dNxA0Mq8DJ2bafF1sx_agHw1U',
    appId: '1:651011193231:ios:c5ca6c509c92cfc22e73fa',
    messagingSenderId: '651011193231',
    projectId: 'kiet-olx',
    storageBucket: 'kiet-olx.appspot.com',
    iosClientId: '651011193231-8h5of7ct9ofkoj41huf7cphck3igccsk.apps.googleusercontent.com',
    iosBundleId: 'com.example.kietOlx',
  );
}
